name: Deploy React App to GitHub Pages

on:
    release:
        types: [published]  # Trigger the workflow when a new release is published

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Deploy React app to GitHub Pages
        uses: omkartapale/react-deployment-gh-pages@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Authentication token for pushing to gh-pages
          branch: gh-pages  # Specify the branch to deploy to